name: Power Platform CI

on:
  push:
    branches:
      - main

jobs:
  export-solution:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Power Platform CLI
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Verify PAC CLI Installation
        shell: pwsh
        run: |
          pac help